#!/usr/bin/python

import sys

import helpers_fritz


fd = helpers_fritz.fritz_fetch()

if 'config' in sys.argv:
    print 'graph_title Fritzbox upload and download'
    print 'graph_vlabel Kbyte/s'
    print 'graph_category network'
    print 'graph_scale no'
    print 'graph_height 250'
    print 'graph_args -l %d -u %d  -r'%(
        -fd['upstream']/(8*1000),
         fd['downstream']/(8*1000),
        )

    print 'down.label Download'
    print 'down.draw  AREA'
    print 'down.type  GAUGE'

    print 'up_bg.label Upload (background)'
    print 'up_bg.draw  AREA'
    print 'up_bg.type  GAUGE'
    
    print 'up_df.label Upload (default)'
    print 'up_df.draw  STACK'
    print 'up_df.type  GAUGE'
    
    print 'up_im.label Upload (important)'
    print 'up_im.draw  STACK'
    print 'up_im.type  GAUGE'
    
    print 'up_rt.label Upload (realtime)'
    print 'up_rt.draw  STACK'
    print 'up_rt.type  GAUGE'
    
else:
    print 'down.value %d'%(   max(fd['ds_bps_curr'])/1000,             ) 
    print 'up_bg.value %d'%( -max(fd['us_background_bps_curr'])/1000, )
    print 'up_df.value %d'%( -max(fd['us_default_bps_curr'])/1000, )
    print 'up_im.value %d'%( -max(fd['us_important_bps_curr'])/1000, )
    print 'up_rt.value %d'%( -max(fd['us_realtime_bps_curr'])/1000, )
